<?php

use Fuel\Core\Asset;

?>

<!-- Image Map Generated by http://www.image-map.net/ -->
<map name="map_map">
	<area target="" alt="Aminte THOMANN"
		title="Aminte THOMANN (aminte.thomann@inrap.fr)"
		href="mailto:aminte.thomann@inrap.fr"
		coords="280,496,571,527" shape="rect">
	<area target="" alt="Rozenn COLLETER"
		title="Rozenn COLLETER (rozenn.colleter@inrap.fr)"
		href="mailto:rozenn.colleter@inrap.fr"
		coords="277,536,577,565" shape="rect">
	<area target="" alt="Raphaëlle LEFEBVRE"
		title="Raphaëlle LEFEBVRE (raphaelle.lefebvre@inrap.fr)"
		href="mailto:raphaelle.lefebvre@inrap.fr"
		coords="274,575,608,608" shape="rect">
	<area target="" alt="Noémie GRYSPERT"
		title="Noémie GRYSPEIRT (noemie.gryspeirt@inrap.fr)"
		href="mailto:noemie.gryspeirt@inrap.fr"
		coords="966,178,1149,252" shape="rect">
	<area target="" alt="Cyrille LE FORESTIER"
		title="Cyrille LE FORESTIER (cyrille.le-forestier@inrap.fr)"
		href="mailto:cyrille.le-forestier@inrap.fr"
		coords="764,440,1112,478" shape="rect">
	<area target="" alt="Nathalie AMEYE"
		title="Nathalie AMEYE (nathalie.inrap@gmail.com)"
		href="mailto:nathalie.inrap@gmail.com"
		coords="769,485,1028,521" shape="rect">
	<area target="" alt="Camille COLONNA"
		title="Camille COLONNA (camille.colonna@inrap.fr)"
		href="mailto:camille.colonna@inrap.fr"
		coords="767,526,1062,555" shape="rect">
	<area target="" alt="Jérôme LIVET"
		title="Jérôme LIVET (jerome.livet@inrap.fr)"
		href="mailto:jerome.livet@inrap.fr"
		coords="720,714,941,745" shape="rect">
	<area target="" alt="Fanny CHENAL"
		title="Fanny CHENAL (fanny.chenal@inrap.fr)"
		href="mailto:fanny.chenal@inrap.fr"
		coords="1229,395,1471,429" shape="rect">
	<area target="" alt="Éric BOES"
		title="Éric BOES (eric.boes@inrap.fr)"
		href="mailto:eric.boes@inrap.fr"
		coords="1385,470,1229,434" shape="rect">
	<area target="" alt="Fanny LA ROCCA"
		title="Fanny LA ROCCA (fanny.larocca@inrap.fr)"
		href="mailto:fanny.larocca@inrap.fr"
		coords="1226,476,1495,509" shape="rect">
	<area target="" alt="Céline PARESYS"
		title="Céline PARESYS (cecile.paresys@inrap.fr)"
		href="mailto:cecile.paresys@inrap.fr"
		coords="1122,742,1379,778" shape="rect">
	<area target="" alt="Isabelle SOUQUET-LEROY"
		title="Isabelle SOUQUET-LEROY (isabelle.souquet-leroy@inrap.fr)"
		href="mailto:isabelle.souquet-leroy@inrap.fr"
		coords="528,1008,942,1047" shape="rect">
	<area target="" alt="Patrice GEORGES"
		title="Patrice GEORGES (patrice.georges@inrap.fr)"
		href="mailto:patrice.georges@inrap.fr"
		coords="531,1050,814,1086" shape="rect">
	<area target="" alt="Thomas ROMON"
		title="Thomas ROMON (thomas.romon@inrap.fr)"
		href="mailto:thomas.romon@inrap.fr"
		coords="477,1208,741,1294" shape="rect">
	<area target="" alt="Jean-Luc GISCLON"
		title="Jean-Luc GISCLON (jean-luc.gisclon@inrap.fr)"
		href="mailto:jean-luc.gisclon@inrap.fr"
		coords="1095,1040,1391,1074" shape="rect">
	<area target="" alt="Richard DONAT"
		title="Richard DONAT (richard.donat@inrap.fr)"
		href="mailto:richard.donat@inrap.fr"
		coords="862,1292,1107,1328" shape="rect">
	<area target="" alt="Sylvie DUCHESNE"
		title="Sylvie DUCHESNE (sylvie.duchesne@inrap.fr)"
		href="mailto:sylvie.duchesne@inrap.fr"
		coords="862,1337,1151,1369" shape="rect">
</map>

<div class="container">
	<h1 class="mt-2 text-center">Carte des référents</h1>
	
	<p class="text-muted text-center">Cette carte représente les référents de chaque région.</p>
</div>

<div id="map_container" style="height: 80vh; overflow: hidden;">
	<?= Asset::img("map_ref.jpg", array("usemap" => "#map_map", "id" => "map_ref")) ?>
</div>
